name: Build PyPI package and Binder image

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Move tag
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/latest-release",
              })
            } catch (e) {
              console.log("Tag does not exist." + e)
            }
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/latest-release",
              sha: context.sha
            })

  build-binder-image:
    needs: move-tag
    uses: ./.github/workflows/build_for_Binder.yml

  build-publish-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==${{ vars.POETRY_VERSION }}
        shell: bash

      - name: Poetry path
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build and publish FAST-OAD-core to PyPI
        env:
          TOKEN: ${{ secrets.PyPI }} # do not use the secret directly in run command, it would write it plainly in the log
        run: |
          poetry build
          poetry config pypi-token.pypi "$TOKEN"
          ls -la dist/ # list the contents of the dist folder to check that the package was built correctly
          poetry publish --skip-existing --dist-dir dist
        shell: bash

      - name: build and publish FAST-OAD
        env:
          TOKEN: ${{ secrets.PyPI }} # do not use the secret directly in run command, it would write it plainly in the log
        run: |
          cd release # move to the release folder, which contains the pyproject.toml for the FAST-OAD umbrella package
          cp ../README.md . # copy the README to the release folder, so that it is included in the package
          VERSION=$(poetry -C .. version -s)
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/g" pyproject.toml # replace the version placeholder in the pyproject.toml with the actual version
          poetry version "$VERSION" 
          poetry build
          poetry config pypi-token.pypi "$TOKEN"
          ls -la dist/ # list the contents of the dist folder to check that the package was built correctly
          poetry publish --skip-existing --dist-dir dist
        shell: bash
